# Generated by Django 4.2.21 on 2025-08-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcodeid', models.CharField(blank=True, default=0, max_length=50, null=True, unique=True)),
                ('heel', models.FloatField(blank=True, default=0, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gas_filling_cylinders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('packaging_instruction', models.TextField(blank=True, null=True)),
                ('field_instruction', models.TextField(blank=True, null=True)),
                ('fill_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], default='OUTSTANDING', max_length=11)),
            ],
            options={
                'db_table': 'gas_filling_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(choices=[('PFLUERO', 'Pfluero'), ('CARBON', 'Carbon'), ('CHEMICALS', 'Chemicals')], max_length=50)),
                ('cylinder_size', models.CharField(choices=[('BIG', 'Big'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], max_length=50)),
                ('fill_weight', models.FloatField(blank=True, default=0, null=True)),
                ('num_cylinders', models.IntegerField(blank=True, null=True)),
                ('stillage', models.BooleanField(blank=True, default=False, null=True)),
                ('cylinder_type', models.CharField(choices=[('STANDARD', 'Standard'), ('STILLAGE', 'Stillage'), ('TUBE_TRAILER', 'Tube Trailer'), ('ISOTANK', 'Isotank')], max_length=20)),
                ('keep_heel', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='gas_filling.order')),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cylinder_time', models.DateTimeField(blank=True, null=True)),
                ('batch_num', models.IntegerField(blank=True, null=True)),
                ('batch_time', models.DateTimeField(blank=True, null=True)),
                ('tare_weight', models.FloatField(blank=True, default=0, null=True)),
                ('tare_time', models.DateTimeField(blank=True, null=True)),
                ('connection_weight', models.FloatField(blank=True, default=0, null=True)),
                ('connection_time', models.DateTimeField(blank=True, null=True)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pulled_weight', models.FloatField(blank=True, default=0, null=True)),
                ('pulled_time', models.DateTimeField(blank=True, null=True)),
                ('cylinder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='gas_filling.cylinder')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='gas_filling.order')),
            ],
            options={
                'db_table': 'gas_filling_fillings',
            },
        ),
        migrations.CreateModel(
            name='CylinderSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_sets', to='gas_filling.orderline')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_num', models.IntegerField(blank=True, null=True)),
                ('start_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='gas_filling.order')),
            ],
            options={
                'db_table': 'gas_filling_batches',
            },
        ),
    ]
