# Generated by Django 5.2.1 on 2025-07-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcodeid', models.CharField(default=0, max_length=50)),
                ('tare', models.FloatField(default=0)),
                ('test_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gas_filling_cylinders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernum', models.CharField(default=0, max_length=50)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('fill_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gas_filling_orders',
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cylinder', models.CharField(max_length=100)),
                ('cylinder_time', models.DateTimeField(blank=True, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('tare_weight', models.FloatField(blank=True, default=0, null=True)),
                ('tare_time', models.DateTimeField(blank=True, null=True)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='gas_filling.order')),
            ],
            options={
                'db_table': 'gas_filling_fillings',
            },
        ),
    ]
