# Generated by Django 4.2.22 on 2025-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='batch_num',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
