# Generated by Django 5.2.1 on 2025-08-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filling',
            name='order_time',
        ),
    ]
