# Generated by Django 4.2.21 on 2025-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0002_filling_batch_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
