# Generated by Django 4.2.7 on 2025-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0002_cylinder_filling_order_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinder',
            name='num',
        ),
        migrations.AddField(
            model_name='cylinder',
            name='barcodeid',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='test_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filling',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
