# Generated by Django 4.2.21 on 2025-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0002_remove_filling_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='field_instruction',
            new_name='qc_instruction',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='cylinder_size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.CharField(choices=[('OCTAFLUOROPROPANE', 'Octafluoropropane'), ('PERFLUOROBUTANE', 'Perfluorobutane')], max_length=50),
        ),
    ]
