# Generated by Django 4.2.21 on 2025-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0003_rename_field_instruction_order_qc_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='tare',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
