# Generated by Django 4.2.21 on 2025-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0003_order_email_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='batch_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
