# Generated by Django 5.2.1 on 2025-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0004_alter_filling_batch_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='batch_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
