# Generated by Django 4.2.21 on 2025-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0004_cylinder_tare'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
