# Generated by Django 5.2.1 on 2025-06-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0004_alter_filling_cylinder_alter_filling_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cylinder',
            table='gas_filling_cylinders',
        ),
        migrations.AlterModelTable(
            name='filling',
            table='gas_filling_fillings',
        ),
        migrations.AlterModelTable(
            name='order',
            table='gas_filling_orders',
        ),
    ]
