# Generated by Django 4.2.7 on 2025-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0005_alter_filling_batch_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='barcodeid',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='tare',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
