# Generated by Django 4.2.7 on 2025-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0006_cylinder_created_at_cylinder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
