# Generated by Django 4.2.21 on 2025-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0006_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinder',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open '), ('IN_PROGRESS', 'In Progress '), ('PACKED', 'Packed '), ('PASSED', 'Passed '), ('FAILED', 'Failed '), ('REWORKED', 'Reworked '), ('FINISHED', 'Finished ')], default='OPEN', max_length=11),
        ),
    ]
