# Generated by Django 4.2.21 on 2025-07-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0007_filling_connection_time_filling_connection_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder',
            old_name='tare',
            new_name='heel',
        ),
        migrations.RenameField(
            model_name='filling',
            old_name='order_time',
            new_name='batch_time',
        ),
    ]
