# Generated by Django 4.2.22 on 2025-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0007_rename_weight_filling_end_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinder',
            name='test_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='filling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
