# Generated by Django 4.2.21 on 2025-08-30 11:17

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0007_remove_cylinder_start_date_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='tare_time',
            new_name='heel_time',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='tare_weight',
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='tare',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
