# Generated by Django 4.2.7 on 2025-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0007_filling_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='weight',
            new_name='end_weight',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='status',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='time_entered',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='filling',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filling',
            name='tare_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filling',
            name='tare_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cylinder',
            name='test_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='filling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
