# Generated by Django 4.2.22 on 2025-06-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0008_alter_cylinder_test_date_alter_filling_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filling',
            table='gas_filling_fillings',
        ),
    ]
