# Generated by Django 4.2.7 on 2025-06-30 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0008_rename_weight_filling_end_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='filling',
            table='gas_filling_fillings',
        ),
    ]
