# Generated by Django 4.2.21 on 2025-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0008_rename_tare_time_filling_heel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='heel_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
