# Generated by Django 4.2.7 on 2025-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0009_order_created_time_alter_filling_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fill_in',
            new_name='fill_type',
        ),
        migrations.AddField(
            model_name='filling',
            name='cylinder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filling',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordernum',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
