# Generated by Django 4.2.21 on 2025-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0009_order_cylinder_size_order_fill_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
