# Generated by Django 4.2.22 on 2025-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0009_alter_filling_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
