# Generated by Django 4.2.7 on 2025-06-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0010_rename_fill_in_order_fill_type_filling_cylinder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='end_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='filling',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filling',
            name='tare_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
