# Generated by Django 4.2.21 on 2025-07-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0010_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordernum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_num', models.IntegerField(blank=True, null=True)),
                ('start_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='gas_filling.order')),
            ],
            options={
                'db_table': 'gas_filling_batches',
            },
        ),
    ]
