# Generated by Django 4.2.21 on 2025-08-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0010_remove_filling_order_filling_order_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='order_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='gas_filling.orderline'),
            preserve_default=False,
        ),
    ]
