# Generated by Django 4.2.7 on 2025-06-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0011_alter_filling_end_weight_alter_filling_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filling',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='fillings', to='gas_filling.order'),
            preserve_default=False,
        ),
    ]
