# Generated by Django 4.2.21 on 2025-07-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0011_alter_order_ordernum_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordernum',
        ),
    ]
