# Generated by Django 4.2.21 on 2025-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0011_alter_filling_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='line_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
