# Generated by Django 4.2.21 on 2025-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0012_remove_order_ordernum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], default='OUTSTANDING', max_length=11),
        ),
    ]
