# Generated by Django 4.2.7 on 2025-07-30 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0013_remove_order_completed_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cylinder_size', models.CharField(blank=True, max_length=50, null=True)),
                ('fill_weight', models.FloatField(blank=True, default=0, null=True)),
                ('num_cylinders', models.IntegerField(blank=True, null=True)),
                ('stillage', models.BooleanField(blank=True, default=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='gas_filling.order')),
            ],
        ),
        migrations.CreateModel(
            name='CylinderSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cylinder_sets', to='gas_filling.orderline')),
            ],
        ),
    ]
