# Generated by Django 4.2.7 on 2025-09-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0013_alter_batch_batch_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open '), ('CLOSED', 'Closed '), ('IN_PROGRESS', 'In Progress '), ('PACKED', 'Packed '), ('PASSED', 'Passed '), ('FAILED', 'Failed '), ('REWORKED', 'Reworked '), ('FINISHED', 'Finished ')], default='OPEN', max_length=11),
        ),
    ]
