# Generated by Django 4.2.21 on 2025-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0014_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='stillage',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
