# Generated by Django 4.2.21 on 2025-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0014_orderline_cylinderset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_comments',
            new_name='field_instruction',
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='cylinder_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('STILLAGE', 'Stillage'), ('TUBE_TRAILER', 'Tube Trailer'), ('ISOTANK', 'Isotank')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderline',
            name='keep_heel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.CharField(choices=[('PFLUERO', 'Pfluero'), ('CARBON', 'Carbon'), ('CHEMICALS', 'Chemicals')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='cylinder_size',
            field=models.CharField(choices=[('BIG', 'Big'), ('MEDIUM', 'Medium'), ('SMALL', 'Small')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
