# Generated by Django 4.2.7 on 2025-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0014_orderline_cylinderset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PACKED', 'Packed'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REWORKED', 'Reworked'), ('FINISHED', 'Finished')], default='OPEN', max_length=11),
        ),
    ]
