# Generated by Django 4.2.21 on 2025-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0015_remove_orderline_stillage_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='heel_weight_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='cylinder_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='fill_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderline',
            name='num_cylinders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
