# Generated by Django 4.2.21 on 2025-08-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0015_rename_email_comments_order_field_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cylinder_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fill_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num_of_cylinders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
