# Generated by Django 4.2.21 on 2025-09-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0016_filling_heel_weight_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='heel_weight_before',
            new_name='heel_weight_b',
        ),
    ]
