# Generated by Django 4.2.7 on 2025-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0015_alter_order_status'),
        ('gas_filling', '0016_remove_order_cylinder_size_remove_order_fill_size_and_more'),
    ]

    operations = [
    ]
