# Generated by Django 4.2.21 on 2025-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0017_rename_heel_weight_before_filling_heel_weight_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='filling_number',
            field=models.IntegerField(default=1),
        ),
    ]
