# Generated by Django 4.2.21 on 2025-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0018_filling_filling_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='packer_comments',
        ),
        migrations.AddField(
            model_name='order',
            name='analyst_comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
