# Generated by Django 4.2.7 on 2025-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0019_rename_comments_order_packer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='analyst_comments',
            field=models.TextField(default='not yet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packer_comments',
            field=models.TextField(blank=True, default='not yet', null=True),
        ),
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recycle_num', models.IntegerField(blank=True, null=True, unique=True)),
                ('start_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycles', to='gas_filling.order')),
            ],
            options={
                'db_table': 'gas_filling_recycles',
            },
        ),
    ]
