# Generated by Django 4.2.7 on 2025-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0020_alter_order_analyst_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filling',
            name='recycle_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filling',
            name='recycle_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
