# Generated by Django 4.2.7 on 2025-09-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0021_filling_recycle_num_filling_recycle_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stillage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('end_weight', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pulled_weight', models.FloatField(blank=True, default=0, null=True)),
                ('pulled_time', models.DateTimeField(blank=True, null=True)),
                ('filling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stillages', to='gas_filling.filling')),
            ],
            options={
                'db_table': 'gas_filling_stillages',
            },
        ),
    ]
