# Generated by Django 4.2.7 on 2025-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0022_stillage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stillage',
            name='stillage_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
