# Generated by Django 4.2.7 on 2025-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0023_stillage_stillage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stillage',
            name='stillage_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stillage',
            unique_together={('filling', 'stillage_number')},
        ),
    ]
