# Generated by Django 4.2.7 on 2025-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0024_alter_stillage_stillage_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stillage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stillage',
            name='stillage_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='stillage',
            name='stillage_number',
        ),
    ]
