# Generated by Django 4.2.21 on 2025-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0025_alter_stillage_unique_together_stillage_stillage_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='export_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='import_certificate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
