# Generated by Django 4.2.21 on 2025-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0026_order_export_certificate_order_import_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='heel_weight_b',
            new_name='empty_weight',
        ),
        migrations.RenameField(
            model_name='filling',
            old_name='heel_weight',
            new_name='final_weight',
        ),
        migrations.RenameField(
            model_name='filling',
            old_name='heel_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='filling',
            name='final_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filling',
            name='start_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
