# Generated by Django 4.2.21 on 2025-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0027_rename_heel_weight_b_filling_empty_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
