# Generated by Django 4.2.21 on 2025-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0028_alter_batch_batch_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='recycle_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
