# Generated by Django 4.2.21 on 2025-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0029_alter_recycle_recycle_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='import_certificate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
