# Generated by Django 4.2.21 on 2025-09-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0030_alter_order_import_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport_company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='import_certificate',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
