# Generated by Django 4.2.7 on 2025-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0031_order_transport_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open '), ('CLOSED', 'Closed '), ('IN_PROGRESS', 'In Progress '), ('PACKED', 'Packed '), ('PASSED', 'Passed '), ('FAILED', 'Failed '), ('REWORKED', 'Reworked '), ('FINISHED', 'Finished '), ('DISPATCHED', 'Dispatched ')], default='OPEN', max_length=11),
        ),
    ]
