# Generated by Django 5.2.6 on 2025-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0032_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.IntegerField(db_column='TransactionID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='TransactionDateTime')),
                ('weight', models.DecimalField(db_column='NetWeight', decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'dbo.tbTransactionLookUpData',
                'managed': False,
            },
        ),
    ]
