# Generated by Django 4.2.7 on 2025-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0033_weighing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stillage',
            name='final_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stillage',
            name='final_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterModelTable(
            name='weighing',
            table='tbTransactions',
        ),
    ]
