# Generated by Django 5.2.6 on 2025-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0034_stillage_final_time_stillage_final_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.CharField(choices=[('OCTAFLUOROPROPANE', 'Octafluoropropane'), ('PERFLUOROBUTANE', 'Perfluorobutane')], default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycle',
            name='product',
            field=models.CharField(choices=[('OCTAFLUOROPROPANE', 'Octafluoropropane'), ('PERFLUOROBUTANE', 'Perfluorobutane')], default='None', max_length=50),
            preserve_default=False,
        ),
    ]
