# Generated by Django 5.2.6 on 2025-11-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0035_batch_product_recycle_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filling',
            old_name='batch_num',
            new_name='batch_id',
        ),
        migrations.RenameField(
            model_name='filling',
            old_name='recycle_num',
            new_name='recycle_id',
        ),
    ]
