# Generated by Django 5.2.6 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0036_rename_batch_num_filling_batch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filling',
            name='batch_time',
        ),
        migrations.RemoveField(
            model_name='filling',
            name='recycle_time',
        ),
        migrations.AddField(
            model_name='filling',
            name='stillage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gas_filling.orderline'),
        ),
    ]
