# Generated by Django 5.2.6 on 2025-11-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0037_remove_filling_batch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filling',
            name='stillage',
        ),
        migrations.AddField(
            model_name='filling',
            name='abandoned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Stillage',
        ),
    ]
