# Generated by Django 4.2.22 on 2025-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_filling', '0002_cylinder_filling_order_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='cylinder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='filling',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
