"""
Django settings for f2db project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from f2db import secret
import os

VERSION = '0.1'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v7v_cee5bs-gnc!2*2xtc8b(x(phyde4%c0m5c!$_4+i1n(4q$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['andyj05', 'localhost', '127.0.0.1', 'f2-app01', '10.0.0.245']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'computers.apps.ComputersConfig',
    'gas_filling.apps.GasFillingConfig',
    'power.apps.PowerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f2db.urls'

WSGI_APPLICATION = 'f2db.wsgi.application'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': ['C:\\django\\f2db_py\\templates'],
        'DIRS': [BASE_DIR / 'templates'],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            # These are values added to the context when a templae is processed
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # info about logged in user
                'django.contrib.auth.context_processors.auth',
                # flash message
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                # custom library useable in templates, load in the template with the key
                'helpers':'templatetags.helpers',
                #'cylinders_helpers':'cylinders.templatetags.cylinders_helpers',
            },
        },
    },
]




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# https://docs.djangoproject.com/en/5.0/ref/databases/

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "f2db",# if os.environ['f2_mode'] == 'prod' else "f2db_py",
        "USER": "postgres",
        "PASSWORD": secret.password,
        "HOST": "localhost",
        "PORT": 5432,
    },
    # 'idhammar': {
        # 'ENGINE': 'sql_server.pyodbc',
        # 'NAME': 'Idhammar_v12_live',
        # 'PORT':'',
        # 'OPTIONS':{
            # 'driver':'ODBC Driver 17 for SQL Server',
            # 'dsn':'Idhammar_17',
        # },
    # },
}






DATABASE_ROUTERS = ['f2db.db_router.DbRouter']



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

DB_MANAGED = False

TEST_RUNNER = 'f2db.test_runner.ManagedModelTestRunner'

EMAIL_HOST = 'f2chemicals-com.mail.protection.outlook.com'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'f2db@f2chemicals.com'
EMAIL_PORT = 25
ACCOUNT_EMAIL_VERIFICATION = 'none'
EMAIL_USE_SSL = False