# Generated by Django 5.0.6 on 2025-02-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pc', models.IntegerField(blank=True, null=True)),
                ('monitor', models.IntegerField(blank=True, null=True)),
                ('original_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('in_use', models.BooleanField(blank=True, null=True)),
                ('processor', models.IntegerField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('network_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.IntegerField(blank=True, null=True)),
                ('sp', models.CharField(blank=True, max_length=255, null=True)),
                ('product_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('office_version', models.IntegerField(blank=True, null=True)),
                ('office_key', models.CharField(blank=True, max_length=255, null=True)),
                ('second_office_key', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'computers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.IntegerField()),
                ('original_owner', models.CharField(blank=True, max_length=16, null=True)),
                ('owner', models.CharField(blank=True, max_length=16, null=True)),
                ('in_use', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ('device_type', 'id'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StaticIpAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'computer_log_static_ip_addresses',
                'ordering': ('address', 'id'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CyberRiskAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_id', models.IntegerField()),
                ('attack_vector', models.IntegerField()),
                ('scenario', models.TextField(blank=True, null=True)),
                ('safeguards', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('likelihood', models.IntegerField(blank=True, null=True)),
                ('consequences', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('not_relevant', models.BooleanField(blank=True, null=True)),
                ('malware_in_network', models.BooleanField(blank=True, null=True)),
                ('scan_traffic', models.BooleanField(blank=True, null=True)),
                ('data_breach', models.BooleanField(blank=True, null=True)),
                ('network_disruption', models.BooleanField(blank=True, null=True)),
                ('internet_disruption', models.BooleanField(blank=True, null=True)),
                ('access_to_control', models.BooleanField(blank=True, null=True)),
                ('ransomware', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('target_id', 'attack_vector', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CyberTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_type', models.IntegerField()),
            ],
            options={
               # 'abstract': True,
            },
        ),
    ]
