# Generated by Django 5.0.6 on 2025-02-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticipaddress',
            options={'managed': False, 'ordering': ('address', 'id'), 'verbose_name': 'Static IP address', 'verbose_name_plural': 'Static IP addresses'},
        ),
    ]
