# Generated by Django 4.2.7 on 2025-06-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_alter_staticipaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticipaddress',
            options={'managed': True, 'ordering': ('address', 'id'), 'verbose_name': 'Static IP address', 'verbose_name_plural': 'Static IP addresses'},
        ),
    ]
