# Generated by Django 4.2.21 on 2025-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimePoint',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('meter19pd28saltcorridor', models.BigIntegerField()),
                ('meter17slaveharmonicsfilter', models.BigIntegerField()),
                ('meter36hwheatingcontrolpanel', models.BigIntegerField()),
            ],
            options={
                'db_table': 'powermeterreadings',
            },
        ),
    ]
