# Generated by Django 4.2.7 on 2025-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepoint',
            name='meter10pd1packingdepartment',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter11rectifiercell6',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter13harmonicsfilter',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter14carbwashchiller',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter15dbpd2_fluorine',
            field=models.BigIntegerField(db_column='meter15dbpd2(fluorine)', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter16pd13_flutec',
            field=models.BigIntegerField(db_column='meter16pd13(flutec)', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter18cell9',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter20pd3_s',
            field=models.BigIntegerField(db_column='meter20pd3(s)', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter21db31_db32portacabin_offices',
            field=models.BigIntegerField(db_column='meter21db31/db32portacabin/offices', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter22rectifiercell5',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter23rectifiercell3',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter24rectifiercell2',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter2572kwoilheater_r05pure',
            field=models.BigIntegerField(db_column='meter2572kwoilheater(r05pure)', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter26pfcunitdoorwall',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter27rectifiercell7',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter28pfcs_n460752_2',
            field=models.BigIntegerField(db_column='meter28pfcs/n460752/2', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter31rectifiercell4',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter32dhfblockchiller',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter33rectifiercell1',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter34dbpd7',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter35rectifiercell8',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter37pp30',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter38pfcunit466752_1',
            field=models.BigIntegerField(db_column='meter38pfcunit466752/1', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter39fluorinemcc',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timepoint',
            name='meter40flutecmezzfloor',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
