# Generated by Django 5.2.1 on 2025-07-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('events', models.TextField(default='')),
            ],
            options={
                'db_table': 'sales_emails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('export_statement', models.TextField(blank=True, null=True)),
                ('tariff', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('currency', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_zones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('packing_note', models.TextField(blank=True, null=True)),
                ('currency', models.IntegerField(default=0)),
                ('product_range', models.IntegerField(default=0)),
                ('specs', models.ManyToManyField(to='samples.spec')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.zone')),
            ],
            options={
                'db_table': 'sales_customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('our_ref', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_ref', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_cost', models.IntegerField(blank=True, null=True)),
                ('sales_comments', models.TextField(blank=True, null=True)),
                ('packager_comments', models.TextField(blank=True, null=True)),
                ('dispatcher_comments', models.TextField(blank=True, null=True)),
                ('date_placed', models.DateField(blank=True, null=True)),
                ('date_required', models.DateField(blank=True, null=True)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('status_log', models.TextField(default='')),
                ('courier', models.CharField(blank=True, max_length=32, null=True)),
                ('courier_ref', models.CharField(blank=True, max_length=32, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
            options={
                'db_table': 'sales_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_volume', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('cost_per_kg', models.IntegerField(blank=True, null=True)),
                ('packing_note', models.TextField(blank=True, null=True)),
                ('date_packed', models.DateField(blank=True, null=True)),
                ('packed_by', models.CharField(blank=True, max_length=32, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.spec')),
            ],
            options={
                'db_table': 'sales_lines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(blank=True, max_length=16, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.product')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.zone')),
            ],
            options={
                'db_table': 'sales_instructions',
                'managed': True,
            },
        ),
    ]
